import type { Package } from "../core/models/model";

export const monthlyPackages: Package[] = [
  {
    id: "monthly-basic",
    title: "Basic Plan",
    price: "150 EGP",
    features: [
      { id: "1", text: "Access to basic content", included: true },
      { id: "2", text: "Standard support", included: true },
      { id: "3", text: "HD streaming", included: false },
      { id: "4", text: "Offline mode", included: false },
      { id: "5", text: "No ads", included: false },
      { id: "6", text: "One device only", included: true },
    ],
    buttonText: "Try Now",
  },
  {
    id: "monthly-starter",
    title: "Starter Plan",
    price: "250 EGP",
    features: [
      { id: "1", text: "All Basic features", included: true },
      { id: "2", text: "HD streaming", included: true },
      { id: "3", text: "Ad-free experience", included: false },
      { id: "4", text: "Offline mode", included: false },
      { id: "5", text: "2 devices", included: true },
      { id: "6", text: "Standard support", included: true },
    ],
    buttonText: "Choose Starter",
  },
  {
    id: "monthly-standard",
    title: "Standard Plan",
    price: "350 EGP",
    features: [
      { id: "1", text: "All Starter features", included: true },
      { id: "2", text: "Offline mode", included: true },
      { id: "3", text: "Ad-free experience", included: true },
      { id: "4", text: "3 devices", included: true },
      { id: "5", text: "Priority support", included: false },
      { id: "6", text: "Basic analytics", included: false },
    ],
    buttonText: "Choose Standard",
  },
  {
    id: "monthly-plus",
    title: "Plus Plan",
    price: "400 EGP",
    features: [
      { id: "1", text: "All Standard features", included: true },
      { id: "2", text: "Priority support", included: true },
      { id: "3", text: "Custom profile", included: true },
      { id: "4", text: "Early access updates", included: false },
      { id: "5", text: "4 devices", included: true },
      { id: "6", text: "Basic analytics", included: true },
    ],
    buttonText: "Go Plus",
  },
  {
    id: "monthly-pro",
    title: "Pro Plan",
    price: "500 EGP",
    features: [
      { id: "1", text: "All Plus features", included: true },
      { id: "2", text: "Advanced analytics", included: true },
      { id: "3", text: "Priority response", included: true },
      { id: "4", text: "Custom branding", included: false },
      { id: "5", text: "Team management", included: true },
      { id: "6", text: "5 devices", included: true },
    ],
    buttonText: "Get Pro",
  },
  {
    id: "monthly-premium",
    title: "Premium Plan",
    price: "650 EGP",
    features: [
      { id: "1", text: "All Pro features", included: true },
      { id: "2", text: "Custom branding", included: true },
      { id: "3", text: "Dedicated support", included: true },
      { id: "4", text: "Analytics dashboard", included: true },
      { id: "5", text: "API access", included: false },
      { id: "6", text: "Unlimited devices", included: true },
    ],
    buttonText: "Get Premium",
  },
  {
    id: "monthly-enterprise",
    title: "Enterprise Plan",
    price: "800 EGP",
    features: [
      { id: "1", text: "All Premium features", included: true },
      { id: "2", text: "API access", included: true },
      { id: "3", text: "Custom integrations", included: true },
      { id: "4", text: "Dedicated account manager", included: true },
      { id: "5", text: "Team dashboard", included: true },
      { id: "6", text: "Full analytics", included: true },
    ],
    buttonText: "Enterprise Access",
  },
  {
    id: "monthly-ultimate",
    title: "Ultimate Plan",
    price: "1000 EGP",
    features: [
      { id: "1", text: "All Enterprise features", included: true },
      { id: "2", text: "Unlimited API calls", included: true },
      { id: "3", text: "Custom SLA contract", included: true },
      { id: "4", text: "Lifetime updates", included: true },
      { id: "5", text: "24/7 personal support", included: true },
      { id: "6", text: "Unlimited users & devices", included: true },
    ],
    buttonText: "Go Ultimate",
  },
];


export const yearlyPackages: Package[] = [
  {
    id: "yearly-basic",
    title: "Basic Plan",
    price: "1500 EGP",
    features: [
      { id: "1", text: "Access to basic content", included: true },
      { id: "2", text: "Standard support", included: true },
      { id: "3", text: "HD streaming", included: false },
      { id: "4", text: "Offline mode", included: false },
      { id: "5", text: "No ads", included: false },
      { id: "6", text: "One device only", included: true },
    ],
    buttonText: "Try Yearly",
  },
  {
    id: "yearly-starter",
    title: "Starter Plan",
    price: "2500 EGP",
    features: [
      { id: "1", text: "All Basic features", included: true },
      { id: "2", text: "HD streaming", included: true },
      { id: "3", text: "Ad-free experience", included: false },
      { id: "4", text: "Offline mode", included: false },
      { id: "5", text: "2 devices", included: true },
      { id: "6", text: "Standard support", included: true },
    ],
    buttonText: "Choose Yearly Starter",
  },
  {
    id: "yearly-standard",
    title: "Standard Plan",
    price: "3500 EGP",
    features: [
      { id: "1", text: "All Starter features", included: true },
      { id: "2", text: "Offline mode", included: true },
      { id: "3", text: "Ad-free experience", included: true },
      { id: "4", text: "3 devices", included: true },
      { id: "5", text: "Priority support", included: false },
      { id: "6", text: "Basic analytics", included: false },
    ],
    buttonText: "Choose Yearly Standard",
  },
  {
    id: "yearly-plus",
    title: "Plus Plan",
    price: "4000 EGP",
    features: [
      { id: "1", text: "All Standard features", included: true },
      { id: "2", text: "Priority support", included: true },
      { id: "3", text: "Custom profile", included: true },
      { id: "4", text: "Early access updates", included: false },
      { id: "5", text: "4 devices", included: true },
      { id: "6", text: "Basic analytics", included: true },
    ],
    buttonText: "Go Yearly Plus",
  },
  {
    id: "yearly-pro",
    title: "Pro Plan",
    price: "5000 EGP",
    features: [
      { id: "1", text: "All Plus features", included: true },
      { id: "2", text: "Advanced analytics", included: true },
      { id: "3", text: "Priority response", included: true },
      { id: "4", text: "Custom branding", included: false },
      { id: "5", text: "Team management", included: true },
      { id: "6", text: "5 devices", included: true },
    ],
    buttonText: "Get Yearly Pro",
  },
  {
    id: "yearly-premium",
    title: "Premium Plan",
    price: "6500 EGP",
    features: [
      { id: "1", text: "All Pro features", included: true },
      { id: "2", text: "Custom branding", included: true },
      { id: "3", text: "Dedicated support", included: true },
      { id: "4", text: "Analytics dashboard", included: true },
      { id: "5", text: "API access", included: false },
      { id: "6", text: "Unlimited devices", included: true },
    ],
    buttonText: "Get Yearly Premium",
  },
  {
    id: "yearly-enterprise",
    title: "Enterprise Plan",
    price: "8000 EGP",
    features: [
      { id: "1", text: "All Premium features", included: true },
      { id: "2", text: "API access", included: true },
      { id: "3", text: "Custom integrations", included: true },
      { id: "4", text: "Dedicated account manager", included: true },
      { id: "5", text: "Team dashboard", included: true },
      { id: "6", text: "Full analytics", included: true },
    ],
    buttonText: "Enterprise Yearly",
  },
  {
    id: "yearly-ultimate",
    title: "Ultimate Plan",
    price: "10000 EGP",
    features: [
      { id: "1", text: "All Enterprise features", included: true },
      { id: "2", text: "Unlimited API calls", included: true },
      { id: "3", text: "Custom SLA contract", included: true },
      { id: "4", text: "Lifetime updates", included: true },
      { id: "5", text: "24/7 personal support", included: true },
      { id: "6", text: "Unlimited users & devices", included: true },
    ],
    buttonText: "Go Yearly Ultimate",
  },
];
